### ISSUE TITLE
All autoplaylists broken - "Couldn't open the playlist - please try again"

### ISSUE THREAD

**Issue by yokaiichi** [simon-weber/Autoplaylists-for-Google-Music#104]
This morning all autoplaylist functionality seems broken in Chrome's Play Music app. The [auto] playlists are shown in my library, but clicking on any of them results in the message shown in description above.

I've tried Ctrl-F5. I've tried closing and reopening the browser. I've tried using the Play Music app's Settings > Refresh Library. I've tried changing the sync time from 10 to 1 minutes, saving, and waiting. I've tried disabling the Autoplaylists extension. Nothing works.

Also note that I've tried this on two entirely different computers, and the symptoms are identical.

Chrome version is reported as Version 54.0.2840.71 m
Autoplaylists version is reported a 2.0.4
Windows 10 on a Surface Pro 3 and also on a generic gaming rig

**Comment by simon-weber** [comment]
Hm, sorry for the trouble. I checked my GA and sentry data, and I don't see anything to indicate a spike in syncing problems for other users. My setup is also working fine this morning.

Usually when I've seen this happen it's because Google's servers were overloaded, often after adding new autoplaylists that were syncing often. Can you try disabling the extension for up to 24 hours and checking back in ocassionally to see if it's fixed the problem? If that works, then bumping up the sync period should be a good workaround, since it'll limit the amount of load on Google. The right value for you will depend on how exactly you use your autoplaylists - eg, for people who use autoplaylists to generate a set of songs to cache on mobile, values as high as one day work well - but I'd recommend starting around an hour.

Of course, as Slack puts it, this is "a solution which I suggest to you now only with great regret and self-loathing". I still don't know exactly why Google can't keep up with many frequently-changing playlists (I suspect it's a similar reason to why they still have a 1k playlist length limit), but I'm optimistic that https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/97 will help.

**Comment by yokaiichi** [comment]
Disabling the extension for 24 hours seens to have fixed the problem. I reset the Sync interval to 720 minutes (12 hours) before disabling it yesterday. Just re-enabled the extension and things still seem to work correctly. Leaving the sync interval at 720 and crossing fingers!

**Comment by simon-weber** [comment]
Phew, that's good to hear. Let me know what sync interval you eventually arrive at. Unless I get the api change done really soon, I may want to push people towards higher values in the meantime.

**Comment by yokaiichi** [comment]
Well, there's a significant problem with this workaround. Apparently, if the sync event tries to occur if you have no browser tab open to Google Play Music (or if your computer is shut down entirely), then nothing at all happens. Nothing ever gets synced unless you're sitting online and ready to go at the next sync interval.  So a long interval like 720 minutes simply isn't practical. For that matter, even 60 minutes is too long.

**Comment by simon-weber** [comment]
https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/91 addressed what sounds like a similar situation: maybe there's a bug in that code?

What should happen is that if the sync period passes while you're offline, then the next time you open a Music tab a sync should happen immediately (to catch up to the missed one). Is that what you're seeing?

**Comment by yokaiichi** [comment]
I actually deleted my comment about the sync not working a day later because I realized that one particular playlist did NOT have a LastPlayed earlier than 180 days ago criteria. I've added that clause and will see what happens by tomorrow. :)

**Comment by confidentjohn** [comment]
I have this exact issue this morning. In the web browser i cannot open any playlists, they all appear blank.

However the Android App still has tracks in them. 

I have disabled the extension and will report back. 

Otherwise...I love this app. Thank you

**Comment by simon-weber** [comment]
@confidentjohn huh, can you think of any recent changes in usage that could have triggered it? My current theory would expect that eg a bunch of new playlists were created or more syncs happened than usual (maybe by lowering the interval or leaving the page up). If that's not the case and Google just does this sometimes under normal use this becomes more troubling.

**Comment by confidentjohn** [comment]
Well im completely new to this extension, so since sunday i have created about 5 playlists.

They were all working fine, and i set the refresh to every 30 minutes.

Then yesterday my Not played playlist stopped working, so i deleted it and re created it, (It had a different name) and this worked fine.

Until this morning. I have the extension disabled now and removed all playlists.

Cheers

John

**Comment by confidentjohn** [comment]
Hi, just to add to this, i think this is a google issue. I just tried to create a manual playlist. 

The playlist created but no tracks were added, i can't even delete it.

**Comment by confidentjohn** [comment]
Hi

So i still have issues today, in the console I am getting the following error,

failed to sync playlist Not Played unexpected getPlaylistContents response: [
  [
    2,
    2,
    0,
    0
  ]
]

**Comment by simon-weber** [comment]
Can you try disabling the extension for a day or two? From what I've seen from other folks, it takes Google quite a while to recover when it's in this state.

If that fixes it, I'd suggest re-enabling and changing the sync interval to something much higher. 720 (12 hours) seems like a safe choice.

**Comment by simon-weber** [comment]
Can you try upgrading and [enabling the new syncing apis described here](https://groups.google.com/forum/#!topic/autoplaylists-for-google-music-announcements/fyQ9j-09GNo)? I'm hopeful it'll fix this.

**Comment by simon-weber** [comment]
Feel free to open a new issue if this is still a problem.
