### ISSUE TITLE
playlists not syncing across computers (chrome sync storage)

### ISSUE THREAD

**Issue by Leviathan1753** [simon-weber/Autoplaylists-for-Google-Music#115]
Not seeing proper syncs of my playlists between my work and home computer.  

Here's what I know:
1)  I've logged into chrome with the same email on both computers
2)  My bookmarks and stuff seem to sync
3)  My autoplaylist definitions do not.
4)  All my autoplaylist results from both locations are showing up in my google music
5)  I can update the respective autoplaylist definition at the computer I created it, and I see the results as expected
6)  I've never had good experiences/luck with chrome sync.  I've had bookmark syncing issues before (not right atm), so it wouldn't surprise me if there was some chrome problems here, too.  Not sure if it's you or me, but just putting feelers out to see.

Any ideas? 
Also, do you know where the files are located locally?  Perhaps I can just merge the listings myself if worse comes to worse

Thanks!  BTW, loving the plugin so far.

**Comment by simon-weber** [comment]
Huh! I haven't heard of anyone running into this before. I would have guessed I'd be a good test case for it: I sync across 3 different OSes and usually have different chrome versions.

Besides the (probably-unhelpful) tips [here](https://support.google.com/chrome/answer/1181420?hl=en), it might be worth [checking the autoplaylist logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs). I don't have any other great ideas, though.

> Also, do you know where the files are located locally?

I've never dug into Chrome's layout on disk, but I have used [this extension](https://chrome.google.com/webstore/detail/storage-area-explorer/ocfjjjjhkpapocigimmppepjgfdecjkb) to edit playlists directly. I think a straight import/export of the chrome.sync.storage tab should work, though you'll want to reload the extension after changing anything. A word of warning: I usually leave this extension disabled, since it messed up my storage in some way I can't remember.

**Comment by Leviathan1753** [comment]
Alright, I'll assume it's just me for now, as I've had problems before.  I'll toy around and see if I can figure anything out by monday or so.

**Comment by Leviathan1753** [comment]
I think I fixed it by following this:  http://www.techrepublic.com/blog/google-in-the-enterprise/steps-to-resolve-chrome-bookmark-synchronization-issues/

Just google being buggy, I guess

**Comment by simon-weber** [comment]
Glad you got it working! And thanks for the link; it'll be useful if anyone else runs into this later.
