### ISSUE TITLE
Cannot read property 'tracks' of undefined

### ISSUE THREAD

**Issue by recacha** [simon-weber/Autoplaylists-for-Google-Music#139]
Autoplaylist does not work. When I click on "Test" I get this error:
```
extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: Cannot read property 'tracks' of undefined
    at chrome.runtime.sendMessage.response (chrome-extension://blbompphddfibggfmmfcgjjoadebinem/js-built/playlist_editor.js:5540:23)
```

**Comment by simon-weber** [comment]
Sorry about that! Can you try reloading with https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension? Sometimes this can be caused by weird problems when initially talking to Google.

If that doesn't fix it, check out your logs with https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs and post back anything that jumps out (or, save them to a file and email them to me and I'll comb through them for you).

**Comment by recacha** [comment]
Great! It works again. I did both steps and I refreshed the playlist.

Thank you very much.

**Comment by simon-weber** [comment]
Glad to hear it! If it ends up happening often, reach out. This should be a rare occurrence.
