### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Yinka** [simon-weber/Autoplaylists-for-Google-Music#143]
No issues with the App, but a couple of questions regarding Google Music itself:

 - Noticed that songs played on my mobile Android/iPad almost always doesn't record/increase playcount (it does record a thumb-up though, but not the playcount), the only reliable way I get playcount these days is to use the web player, anyone has a similar experience / ideas ?

-  I use multiple mobile players; iPad and Android, to play music, sometimes within minutes of each other, how does Google handle playcount sync to its server when this happens? 
     -  When online, is it immediate or at regular interval? 
     -  What happens when device is offline?

This one is about the AutoPlaylists App 
- In what playlist order are changes written to the playlist library by the app, is it random or is it determined by the playlist order in the extension?

Thanks

**Comment by simon-weber** [comment]
I've heard of people [having](https://www.reddit.com/r/googleplaymusic/comments/5lvprg/play_count_through_chromecast_not_updating/) [issues](https://www.reddit.com/r/googleplaymusic/comments/5dqr64/play_counts_not_updating_from_mobile/) with play counts from non-web clients, though I haven't noticed any myself. I haven't heard of any solutions.

From the last time I looked at the traffic, updating the playcount seemed intended to happen a) immediately after finishing a song when online, or b) a few minutes after opening the app once getting connectivity again.

In recent versions of autoplaylists, each periodic sync does roughly this:
* retrieve all changes on Google's end since last sync (tracks/playlists added/removed/updated)
* calculate new contents for all autoplaylists
* find all differences compared to existing autoplaylist contents
* update all autoplaylists at once to match new contents

So, if Google's servers are keeping up, all the remote playlists should get updated at about the same time. The exception is when an autoplaylist definition is changed locally: in that case, it will be synced by itself.

Does that answer your questions?

**Comment by Yinka** [comment]
It does. Thank you.
