### ISSUE TITLE
Playlist updated to empty

### ISSUE THREAD

**Issue by charlesabell5** [simon-weber/Autoplaylists-for-Google-Music#145]
Hello, I have been using your wonderful plugin for a few days now, was working great. Just a few minutes ago I opened the extension to add rating thumb equals none to add more filtering, after clicking test, there is 'no data available in table'. So i removed the rating thumb filter...test.....still showing 'no data available in table'.

I tried saving it then viewing in the actual player but it shows 'this playlist is empty'. Perhaps something changed in the back end of things for Google since yesterday? Or am I doing something wrong? It was working fine before I tried to add the new filter.
![auto-playlists](https://cloud.githubusercontent.com/assets/24857919/24880670/4be7f97c-1e09-11e7-9637-3d453e071582.png)

**Comment by simon-weber** [comment]
Huh! What happens if you delete the playlist entirely, create a new one, then hit "test" without adding any conditions? That should show you your entire library.

If instead it shows 0 matches, there may have been a problem pulling in your library (and the extension thinks you have 0 songs). [Reloading](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension) usually fixes problems like those.

If it still doesn't, then [save your logs to a file](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) and email them to me directly (simon@simonmweber.com) and I'll dig into it.

**Comment by charlesabell5** [comment]
It's working now, i just left open both tabs and checked back just now and it's all updated.

**Comment by simon-weber** [comment]
Not sure what happened, but glad it's working again!
