### ISSUE TITLE
Syncing stopped working

### ISSUE THREAD

**Issue by btalrocks** [simon-weber/Autoplaylists-for-Google-Music#146]
It appears that none of my Autoplaylists for Google Music playlists are syncing for the last couple of days. I've tried creating new ones and they don't show up. Most likely related, also the "test" button isn't popping up with anything.

**Comment by simon-weber** [comment]
Hm, sorry about that! My bet is that there was a problem pulling in your library and now the local cache is in a bad state. [Reloading](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension) usually fixes problems like that.

If you're still seeing issues after a reload, then [save your logs to a file](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) and email them to me directly (simon@simonmweber.com). That should give me enough to dig into it for you.

**Comment by btalrocks** [comment]
Thank you for the quick reply. Shortly after posting the above I uninstalled and reinstalled the chrome extension. I'm guessing all the data was local to that extension because all my saved playlists were gone from the extension. I had to recreate them. Luckily I only had about 5 or 6 so it wasn't a big deal. Will losing the playlists be expected if I uninstall/reinstall? Or was that itself an issue?
To confirm, it is currently working again now after recreating them from scratch.

**Comment by simon-weber** [comment]
Ah, sorry about that. It's expected: the important data is stored in [Google's sync storage](https://developer.chrome.com/extensions/storage#property-sync), which they wipe serverside on uninstalls. I don't have a way to hook uninstall events (until after they happen), so I can't easily warn people about it.

https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/40 would have helped with this. I'll consider this another vote for it. Another thing that could have helped is moving the reload recommendation closer to the UI, since it's a harmless first step to try. I'll ticket that separately.

Anyway, glad to hear things are back to normal!

**Comment by btalrocks** [comment]
I really appreciate the info and thanks for the great product. Keep at it.

**Comment by simon-weber** [comment]
Thanks! Glad it's helpful.

Here's the ticket for moving the reload recommendation forward: https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/147.
