### ISSUE TITLE
All my playlists have disappeared

### ISSUE THREAD

**Issue by brianzam** [simon-weber/Autoplaylists-for-Google-Music#153]
In autoplaylist, I tried editing an autoplaylist which used other playlists in the conditions.  In autoplaylist, the drop down showing available playlist WAS only showing my other autoplaylist playlists.

I re-installed the extension.

Now, autoplayliust is not showing any of my saved autoplaylists.  This is a problem for me as all my playlist management is now using autoplaylists and I am sorting through a large amount of music. I have some scomplicated playlists that took me some time to create, so I need them back please!

It is now showing all my playlists in the drop down to select a playlist in the autoplaylist conditions

Seems very flakey still :-( I'll continue to pay the subscription is this issue gets sorted soon, otherwise, it's just not worth it.

I need my old playlists back - even if it's just the conditions so I can re-create them.

**Comment by simon-weber** [comment]
Ah, sorry. That sucks and I don't think there's anything I can do to easily recover your definitions. My best recommendation is to recreate by hand using the playlist descriptions as a guide (the "Synced by Autoplaylists to contain..." bit). Behind the scenes, Google deletes all your synced data immediately on an uninstall, and the [only hook]( https://developer.chrome.com/extensions/runtime#method-setUninstallURL) available to developers fires after the uninstall happens.

Anyway, I'm not trying to blame this on you: it's on me to figure out the UX around uninstalls (especially since someone else had [the same problem recently](https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/146#issuecomment-295823808)). The best I can think of is putting a note in the UI where the syncing faq is linked; does that sound reasonable? Or, is there somewhere else you'd recommend? I'm tracking that work over in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/147.

**Comment by brianzam** [comment]
Hi Simon,

Isn’t there a backup of the playlists?  If not, then I suggest this is pretty critical seeing as the application isn’t all that reliable yet.

And yes, I’d make it very clear all aver the auto playlist page that uninstalling the extension will remove all your playlists.  I was assuming they were held remotely.

Kind regards,


Brian Zammit

**Comment by simon-weber** [comment]
There's no app-level backup at the moment, though I'll consider this [a vote for it](https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/40). To clarify, definitions are stored remotely on [Google's servers](https://developer.chrome.com/apps/storage), and they should be robust to just about all problems aside from uninstalls (which wipes that store entirely).

Anyway, sorry again for the trouble. I should have some time today to make the copy change, and I'll continue thinking about the best way to implement backups.

**Comment by simon-weber** [comment]
Ok, the copy change is out. I'll continue to track the backup support in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/40. Let me know if there's anything else I can do to help!

**Comment by brianzam** [comment]
Thanks Simon.  I realised that the definitions were in Google music this morning, so it was easy enough to re-create.

Thanks for the app and Keep on improving it, and I’d definitely think back-ups are essential.


Kind regards,


Brian Zammit

Project & Programme Manager and Business Analyst
Accredited DSDM (Agile) PM, PRINCE2, MSP, LEAN 6σ
 

 +447876 394978
 brianzam@gmail.com <mailto:brianzam@gmail.com>
 www.linkedin.com/in/brianzam <http://www.linkedin.com/in/brianzam>
 brianzam101
