### ISSUE TITLE
Wrong google account

### ISSUE THREAD

**Issue by sshwartz** [simon-weber/Autoplaylists-for-Google-Music#155]
When I first loaded the extension, I was prompted for my google username/pwd and I accidentally entered an account I own but not the one with my music.  I tried deleting the extension and reinstalling it from the chrome store but I can't get it to re-prompt me for the correct username.

**Comment by simon-weber** [comment]
Ah I think you'll need to do that from your Google account settings at https://security.google.com/settings/security/permissions. Revoking the permissions for autoplaylists and then [reloading](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension) should trigger the oauth prompt again.

**Comment by sshwartz** [comment]
Thanks Simon.  That fixed the one problem.  Now I have another.  Even though I’m signed in to Google with the correct user (the one that owns Google Music), when I click the Auto Playlists button, I get:

Sorry! Due to restrictions in Google's apis, only the user signed into this Chrome profile can use the extension.

Does this plugin work if there are multiple Chrome users?

**Comment by simon-weber** [comment]
It sounds like you use different users for Chrome and Google Music, which unfortunately isn't supported: the two need to be the same since Google handles authing for Chrome (it happens automatically when you install) while I handle authing for Music (the prompt you reaccepted).

Can you double check that the two don't match? Your Chrome user is the email you see when clicking your name in the top right of Chrome above the extension icon (more instructions [here](https://support.google.com/chrome/answer/185277)), while your Music user is the one from clicking your profile picture in the top right of Google Music below the extension icon.

**Comment by simon-weber** [comment]
Huh. I run the exact same setup (a personal and work chrome profile), so I'm not sure what's different about your case that prevents me from hitting the same issue. I just did some quick testing now and wasn't able to reproduce it.

Let's check that your two accounts match from Google's perspective (which is what the extension is looking at before firing that error). Can you try the following code snippets for me?
* open the extension dev tools console: instructions are [here](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) since it's the same place the logs are kept
* at the bottom of the window next to the `>`, paste this and hit enter:
```
chrome.identity.getProfileUserInfo(i => console.log(i))
```
You should see output that looks like `{email: "me@gmail.com", id: "1234566789"}`. This is the user Chrome is reporting as logged in.
* open a Google Music tab and log in with the same account
* enter the url `javascript:alert(JSON.stringify({id: window.USER_CONTEXT[32], email:window.USER_CONTEXT[12]}))` and press enter. You should see a popup with the same format as the first output.

When I run these, both the email and id match exactly, which is what the extension is checking behind the scenes. Do they match for you?

**Comment by sshwartz** [comment]
Hi Simon,

Really appreciate your help on this.  They do match exactly – see below…

Steve


[cid:image001.png@01D2DCF6.1FC97E50]


[cid:image003.jpg@01D2DCF6.5C645330]

**Comment by simon-weber** [comment]
Huh! It looks like your pictures got swallowed by GitHub's email reply code: can you try uploading them to GitHub directly? You can drag and drop them onto the issue thread at https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/155. Or, you could link to them instead.

Here's the next thing I'd like to try:
* [reload the extension](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension)
* click the page action (which should reproduce the problem)
* [export your logs to a file](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) and email them to me directly (simon@simonmweber.com)

My guess is that since the users match there's something happening afterwards that's the issue. The logs should tell us what that is.

**Comment by sshwartz** [comment]
Simon, it all of a sudden started working.  Sorry but I can’t tell you what I did to get it working.

Now I have another problem.  My goal is to get around the 1000 song limit and create an auto-playlist that combines two playlists that are 500-700 songs each.  So I tried an ANY on the 2 playlists but the auto-playlist only has 300 songs.

**Comment by simon-weber** [comment]
Huh, ok. Well, glad that's working now, and let me know if it happens again!

For the combined autoplaylist, my best bet would be that the playlists have non-library songs in them, which don't currently make it into autoplaylists (tracked in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/119). The workaround for now is to add all the songs in the playlist to your library.

If that doesn't fix it for you, here's some debugging ideas:
* if you create a new, empty autoplaylist and hit "test", does it show all the songs in your library?
* if you add a single "playlist is <one of the two playlists>" rule and test it, does it show all the songs in that playlist?
* can you double check that there aren't duplicate tracks in the two playlists? Autoplaylists will only contain unique songs, so on the off chance there are hundreds of duplicates that could explain the behavior you're seeing.

Let me know how that goes!

**Comment by sshwartz** [comment]
I added all the songs to the library.  Now I get the auto-playlist with 1000 songs.  Is that the limit?

**Comment by simon-weber** [comment]
Sort of. Behind the scenes, autoplaylists are implemented with normal playlists. On Google's end it just looks like you're constantly updating them to match the autoplaylist's conditions. There's no getting around the 1k limit in this sense.

But, the number of tracks an autoplaylist can select is unlimited: this is the number you see when hitting the test button. The usual approach to get around the 1k limit is to [use a random sort](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Tips-and-Tricks#random-sorting) in your autoplaylist: this way, a random 1k subset of your 1k+ tracks end up in the actual playlist each time. This approach tends to work pretty well so long as you're not trying to play over 1k tracks in a single sitting.

Sorted by last played is another common approach.

**Comment by sshwartz** [comment]
Makes sense.  Thanks for all your help!

Steve

**Comment by simon-weber** [comment]
Sure thing!
