### ISSUE TITLE
Couldn't play the playlist. Please try again.

### ISSUE THREAD

**Issue by rehmaj** [simon-weber/Autoplaylists-for-Google-Music#176]
Just purchased this. Synching doesn't seem to be working too well as the new playlists I've created are not synching and now I'm getting an "Couldn't play the playlist. Please try again." error when trying to play any Google Music Playlists. Ideas?

**Comment by simon-weber** [comment]
Roughly how many tracks are in your autoplaylists in total? My guess would be it's a lot (thousands?), and that Google got temporarily overwhelmed by it.

Usually this fixes itself after waiting for a bit.

**Comment by rehmaj** [comment]
They are all in the thousands, yes. Suppose there's no reason I can't lower
them if that's the issue. I'll give that a try.

**Comment by simon-weber** [comment]
Cool. I wouldn't worry about tweaking them down: so long as the autoplaylists aren't changing very frequently it's probably just a one-time thing at the time when they were created together. As far as I've been able to figure out, their backend is sensitive to the number of changes (adds/reorders/deletes) rather than the total number of entries.

**Comment by rehmaj** [comment]
About 45 minutes ago I changed the playlists down to 250 songs each. I
currently have only 7 autoplaylists. I still don't see some of them and
can't access any of them. How long should it take to update?

**Comment by simon-weber** [comment]
I'd expect things to be back to normal after a few hours at most. https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/158 is an example of another issue that I think is caused by the same scaling issues on Google's end.

**Comment by rehmaj** [comment]
Still don't have all my playlists listed and have some with 0 songs. Can't
access them from a web browser, seem to be able to see them with the
Android App. Thoughts? I'm trying another sync now.

**Comment by simon-weber** [comment]
Sounds like Google's catching up, though I'm surprised it's taken this long.

How'd the new sync go? If you're still having issues, try going into settings, clicking the checkbox under "enable change batching" then reloading the extension. There's more context on what it does in https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/144. If it helps in your case I'll probably go ahead with rolling it out to everyone.

**Comment by rehmaj** [comment]
Still no joy. Enabled the checkbox. Still no joy.

Odd issue too. We'll take 1 random playlist. 2000's Country. I can't access
it via Play Music in a web page. I can access it via Android App, it shows
Sync'd just a few minutes ago, but has 0 tracks in it. When I look at it in
the Extension and do a Test it has plenty of tracks there.

Where do we go from here?

**Comment by simon-weber** [comment]
Hm. Especially with the weird differences between the web and mobile app, I'm inclined to just try backing off and waiting one more time. Even if we still need to make changes on our end to get things working smoothly afterwards, it'll at least verify my theory that their servers get overwhelmed and catch up later on.

How about this: 
* [collect your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) after a sync and email them to me
* then, go into settings and change your sync period to 0

This will disable automatic syncing. Avoid manually syncing for 24 hours as well. In the meantime I'll take a look at your logs to see if they're reporting anything helpful back to the client.

My hope is that 24h will be enough to get you back into a normal state, and then the change batching will prevent you from getting there again.

**Comment by rehmaj** [comment]
Logs attached. Plenty of errors for you to review. Sync set to 0.

**Comment by simon-weber** [comment]
Can you email them to me directly? It doesn't look like github's email-to-comment system picked it up.

**Comment by rehmaj** [comment]
Just sent now. Please confirm receipt.

**Comment by simon-weber** [comment]
Got them; thanks!

I took a quick look:
* the `.../plentries?...: the server responded with a status of 500` lines confirm issues on Google's end (it's a generic error code for a serverside error)
* the `rejecting from syncPlaylistMutations` line is a symptom of https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/160. I don't think it's contributing to load, but it doesn't mean that you'll need to eventually recreate the affected autoplaylists.
* the extension noticed that syncs were failing and started preventing them automatically (the "entering backoff" bits). I think this was less useful than intended, though, since that data doesn't survive extension restarts. It's a good example of how https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/72 would improve things, too (you currently can't tell without looking at the logs).

So I don't think there's anything actionable in the short term - I'm still reasonably confident it'll fix itself after waiting long enough - but I'll bump up the priority of those other issues in the long term.

**Comment by rehmaj** [comment]
OK, update. In the web browser I can now get into all the playlists. I've
done nothing else with the extension. Some of them are still either empty
or have less than expected tracks. I'll follow up with you in the morning
for further guidance. Thanks for the responsiveness.

**Comment by rehmaj** [comment]
Same situation this morning. In the web browser I can now get into all the
playlists. I've done nothing else with the extension. Some of them are
still either empty or have less than expected tracks. Where do I go from
here?

**Comment by simon-weber** [comment]
Great, it sounds like Google's end is back to normal. Here's what I'd recommend:
* for playlists that exist locally but don't have a corresponding Google playlist: delete the local playlist and recreate it (this is https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/160 and won't currently fix itself)
* change your sync period to something like 30 to restart automatic syncs (this should fix the playlists that exist but have the incorrect songs, and should be infrequent enough to avoid overwhelming Google again)

Let me know how it goes.

**Comment by simon-weber** [comment]
How's it going? Hope everything is working again!

**Comment by rehmaj** [comment]
Seems like this is working well at this point. Busy week so not much play time. Now if you can just make a volume leveling function that Google would use across the board. :)

**Comment by simon-weber** [comment]
Glad to hear it!

Haha, and yeah, I have no clue why they haven't added leveling. It's something I really want too.
