### ISSUE TITLE
Sorting order based on condition

### ISSUE THREAD

**Issue by oconshien** [simon-weber/Autoplaylists-for-Google-Music#180]
I think currently the sorting methods sort according to each condition.
For example, if I have a playlist with (any: (genre contains hardstyle), (genre contains hardcore)) and sort descending by play count, it will go from most played hardstyle to least played hardstyle, then most played hardcore to least played hardcore.
changing the order of the conditions reverses this tiered ordering.

I believe the sorting occurs after each condition.
maybe allow an option to sort everything regardless of condition? so for example, both genres will be mixed and then sorted in entirety by play count.

**Comment by simon-weber** [comment]
My guess would be this is happening under the hood as a side effect of [lovefield](https://github.com/google/lovefield) indexes.

What happens if you add a random sort before (or maybe after) your playcount sort? I forget exactly how the random sort interacts with others, but it might get you what you want.

**Comment by simon-weber** [comment]
Any luck with this?

**Comment by oconshien** [comment]
sorry, love the extension but not enough to shell $2/mo and my trial ran out :/

**Comment by simon-weber** [comment]
No worries! Let me know if there's something I can add to make it worthwhile.

I'm going to close this issue for now.
