### ISSUE TITLE
Not adding all thumbs-up tracks for an artist

### ISSUE THREAD

**Issue by jblaker** [simon-weber/Autoplaylists-for-Google-Music#191]
I created a simple smart playlist to simply display all songs by U2 with a thumbs-up. The playlist displays 12 songs but should be displaying 22. 

I have "artist" set to "u2" using "equals (case ignored)" and "rating thumb" set to "up" and  "equals (case ignored)". 

I originally had artist and rating thumb set to just equals but used case ignored to see if it made a difference. 

I have tried refreshing the Google Music tab, and opening it in a different tab, and restarting Chrome.

**Comment by simon-weber** [comment]
Sorry for the delay! I was traveling this weekend.

Do the missing songs show up when using the "test" button? If not, my bet would be that you're seeing https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/119, and you should be able to get it working by adding them to your library.

If they do show up when testing but don't make it to Google, then there's some kind of syncing issue. [Send me your logs](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#viewing-your-logs) after triggering a sync and I'll see what I can find out.

**Comment by jblaker** [comment]
Thanks for the reply @simon-weber!

The songs do not show up when using the "test" button and the songs are definitely in my library. Sync log attached. Thanks again!

[sync_log.txt](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/2250756/sync_log.txt)

**Comment by simon-weber** [comment]
Wait, they _don't_ show up when using the test button, right? Then the issue is before syncing happens. Some questions to narrow this down:

* do you have a free or subscription Google Music account?
* are you able to find the missing songs in Google Music by using the search bar at the top? if so, when you right click them do you get an "add to library" prompt?
* if you don't see the prompt, [open the debug interface](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#manually-making-queries), click "run", then click "csv". The file that's created has your entire library as seen by the extension; you can either look through it yourself for the missing songs or send it my way. If they're in there, my guess would be they have something like trailing whitespace that's preventing them from being matched.

**Comment by jblaker** [comment]
- Paid subscription
- I have the songs in another playlist, actually, and if I right click the option I have is to "Remove from Library"

<img width="952" alt="screen shot 2018-08-01 at 3 53 42 pm" src="https://user-images.githubusercontent.com/677534/43545196-31eaeecc-95a3-11e8-905c-4bd08fd413d6.png">
<img width="877" alt="screen shot 2018-08-01 at 3 53 15 pm" src="https://user-images.githubusercontent.com/677534/43545197-31f93fd6-95a3-11e8-8f60-1c49f1b78acd.png">

**Comment by jblaker** [comment]
I did notice some of the songs weren't added (song in playlist was part of Deluxe or Remaster edition and in my library was standard), so adding them did end up adding them to the playlist. 

In the case of Miracle Drug there is only one version of the album and it is in my library but wasn't showing up. I just tested removing it from my library and re-adding it and now it shows up.

**Comment by simon-weber** [comment]
Sure thing. Glad we got it figured out!
