### ISSUE TITLE
Autoplaylists plugin simply does not work on my end

### ISSUE THREAD

**Issue by nononolimits** [simon-weber/Autoplaylists-for-Google-Music#204]
So, I installed the chrome plugin and am running it as a free trial.

When I create a new autoplaylist and hit "test", nothing happens.
When I press "Sync all playlists now", nothing happens.

In Google Play Music, no new playlists get created.
I already tried reloading the plugin (by disabling and enabling it again), I also tried refreshing auth token.

When I even try to run a manual query in chrome-extension://blbompphddfibggfmmfcgjjoadebinem/html/debug.html and press "run" button, nothing happens. This is the query I ran:

const db = dbs[Object.keys(dbs)[0]];
const Track = db.getSchema().table('Track');
db.select().from(Track)
.where(Track.artist.eq('Wire'))
;

I definitely have songs by Wire in my Google Play Music account.

Do mind that I use a free account on Google Play Music and that I only have music on there which I uploaded myself (through Music Manager).

My browser is chrome 76.0.3809.100

**Comment by nononolimits** [comment]
When I hit "Sync all playlists now", then this is console output:

![image](https://user-images.githubusercontent.com/34399288/63153225-196a9000-c00e-11e9-9614-5cc3077506f4.png)

**Comment by simon-weber** [comment]
My guess would be something weird happened when initially retrieving your library, maybe related to auth.

If you don't have anything in the extension you're worried about losing yet, the easiest way to reset everything is to just uninstall and reinstall. If you're still seeing the same thing after that, the logs and/or network tab should point to the root cause -- the current message is helpful, but is probably just fallout from an earlier issue.

**Comment by nononolimits** [comment]
Thanks for your reply!
Tried uninstalling the plugin and installing again. Didn't help.
This should be full output:
[blbompphddfibggfmmfcgjjoadebinem-1565976070813.log](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/3510525/blbompphddfibggfmmfcgjjoadebinem-1565976070813.log)

**Comment by nononolimits** [comment]
And console output of html/playlists.html:

navbar.js:5126 Error: timed out for callback => {
      chrome.runtime.sendMessage({action: 'getStatus'}, status => callback(new Date().getTime() - status.lastSyncInfo.ts < 30000));
    }: [object Arguments]
    at syncpage.js:9274
    at syncpage.js:9315
console.<computed> @ navbar.js:5126
app.getsentry.com/api/66349/store/?sentry_version=7&sentry_client=raven-js%2F3.17.0&sentry_key=ea691c5833f34aa085df5e5aee9a46f3:1 Failed to load resource: the server responded with a status of 403 (FORBIDDEN)

**Comment by nononolimits** [comment]
Maybe also something I should mention: my library has 88.808 songs in it.

**Comment by simon-weber** [comment]
Hm,  that looks like just the background script traceback rather than the full log, though it's named as if it should be the full log. Maybe you've got some levels disabled? Try [reloading](https://github.com/simon-weber/Autoplaylists-for-Google-Music/wiki/Debugging#reloading-the-extension), opening the logs, then selecting "Default" in the dropdown next to the filter textbox. It should look like this afterwards:

![image](https://user-images.githubusercontent.com/950506/63187852-e0421800-c02d-11e9-9f98-716cff18df44.png)

I'd expect to see at least some early messages along the lines of "got verifyToken response" and "opening db". Right-click anywhere + save-as should include those and hopefully point us in the right direction.

I don't think library size should matter too much but it might be an issue if for some reason Google's not writing out an idb for you, which happens sometimes.

**Comment by nononolimits** [comment]
Ah, I know what I did wrong with saving log, I filtered only errors. I now did the same, but now exported complete log:
[blbompphddfibggfmmfcgjjoadebinem-1565984772675.log](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/3510951/blbompphddfibggfmmfcgjjoadebinem-1565984772675.log)

I also tried a different chrome plugin (https://chrome.google.com/webstore/detail/lastfm-for-google-play-mu/phgfbocbablicfiplgfeckpialhcbmkh), so info on that one may be in logs too now. But, that one doesn't seem to work either.

**Comment by simon-weber** [comment]
Perfect; thanks!

It looks like auth is ok, but there's an issue when querying the Google Music tab for your library. Try this:
* close any existing Google Music tabs
* reload the extension
* open a new Google Music tab and open the console in that tab
* filter to "querypage" to just get the extension's logs

It should end up looking something like this:
![image](https://user-images.githubusercontent.com/950506/63196959-89940880-c044-11e9-9c35-78b3ddf303bf.png)

I expect we'll find an error during the queryIDB request.

**Comment by nononolimits** [comment]
I did everything you asked, but when I filter console for "querypage" it comes up with nothing.

This is my latest log:
[blbompphddfibggfmmfcgjjoadebinem-1566025898397.log](https://github.com/simon-weber/Autoplaylists-for-Google-Music/files/3511741/blbompphddfibggfmmfcgjjoadebinem-1566025898397.log)

In it also me trying to press "Sync all playlists now" and doing that same manual query in html/debug.html too.

**Comment by simon-weber** [comment]
Ah, I need the logs from the extension code running in the Google Music tab this time (rather than from the background script, which we'd been looking at previously). So, to be more specific, when you open the Google Music tab and have it selected, hit `ctrl` `shift` `J` or `ctrl` `option` `J`: this should open a console for the tab with the information we need.

**Comment by nononolimits** [comment]
Aha, you're right, I'm getting this:

![image](https://user-images.githubusercontent.com/34399288/63217197-3c965c00-c142-11e9-8879-57b37c0b5ce0.png)

**Comment by simon-weber** [comment]
Ah, excellent! So it was a library size issue after all.

Thanks so much for helping me track this down. I'll look into splitting up that response. It might take some doing since everything's built to assume 1 request == 1 response, so no promises on when I'll get it done.

**Comment by nononolimits** [comment]
Take your time.
If you need more info on my part, or stuff I should try, just let me know.

**Comment by simon-weber** [comment]
Alright, those responses are now batched into 1k track chunks to avoid the limit. You should get the new version automatically -- let me know how it goes!

**Comment by nononolimits** [comment]
Yes, that did the trick!
All is working as should now.

**Comment by simon-weber** [comment]
Great! Thanks for sticking with me while we debugged it.
