### ISSUE TITLE
Playlists via Web UI and Android app are different

### ISSUE THREAD

**Issue by johnrobertlawson** [simon-weber/Autoplaylists-for-Google-Music#22]
I have an autoplaylist with 930 songs through the web UI, and only 21 songs on phone and tablet. I've tried multiple force syncs through Chrome extension, and refresh via the Android app, with no luck. Weird.

**Comment by simon-weber** [comment]
Bizarre. Maybe the android app thinks it should only display downloaded tracks?

**Comment by johnrobertlawson** [comment]
Alas, I toggled and no use!

**Comment by simon-weber** [comment]
Of my three playlists, one was different. The mobile version seemed to be a strict superset of the web version; I could only find duplicate tracks, not anything missing or new.

I was only able to fix this by deleting and recreating the playlist.

This looks like a bug in their mobile client, since gmusicapi's count of tracks agrees with the web version, and gmusicapi uses the same api that their mobile client uses.

**Comment by johnrobertlawson** [comment]
Doesn't seem to be a problem now I've recreated the playlists with the Extension beta.

**Comment by simon-weber** [comment]
Fair enough :+1:

I'll close this for now; feel free to reopen if you run into it again.
