### ISSUE TITLE
Add an option to make string comparisions case-insensitive

### ISSUE THREAD

**Issue by sschuberth** [simon-weber/Autoplaylists-for-Google-Music#27]
That would be useful for badly tagged uploaded-and-not-matched songs.

**Comment by simon-weber** [comment]
Good idea.

If you're eager to have it now, you could make "string equals foo" case insensitive with something like "string matches-regex ^[Ff][Oo][Oo]$". Since I don't expose modifiers I don't think there's an easier way to write it out currently, but this has been useful for matching matching genres with mixed first-character caps (eg "progressive metal" and "Death Metal" both match "[Mm]etal").

**Comment by simon-weber** [comment]
I added new case-insensitive operators for equals, not equals, and matches. They may end up being a bit slow -- I'm not sure how well lovefield uses the index for more complex regexes (if at all).

**Comment by sschuberth** [comment]
Thanks again!
