### ISSUE TITLE
Before/After X days ago

### ISSUE THREAD

**Issue by Yinka** [simon-weber/Autoplaylists-for-Google-Music#56]
Thank you so much for this extension.

I am a little bit confused by the use of before/after in dates like below: (sorry if this is obvious)

**`Last Played` : `Before` :  `15 Days Ago`**  (described as `lastPlayed < 15 days ago`)

**`Last Played` : `After` :  `15 Days Ago`** (described as `lastPlayed > 15 days ago`) 

I will be grateful if you provide a brief explanation.

**Comment by simon-weber** [comment]
Haha, no worries; someone else asked about this previously as well. Check out this explanation and let me know if it clears it up: https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/35#issuecomment-178889135.

If so, I'll clean it up, move it to the faq and link it from the editor. Or, maybe there's a better way to name it that removes the ambiguity? I'd love to hear your thoughts how you'd naturally think about this.

**Comment by PeteRepeat77** [comment]
Can you change the wording to "Within" rather than before, and "More than"  for after? Or are there other arguments that rely on "before" 

Or did I get these backwards again ha ha

**Comment by PeteRepeat77** [comment]
Actually if last played is less than 15 days ago, then that means it was played a long time ago... So when I change the way I think about it all is good but I think within and more than makes more sense to me.

**Comment by Yinka** [comment]
Hi Simon

Thanks for the quick reply and for the link - it helped.

Could you add a date picker:

`Last Played` : `Before` : **31/02/2015**
or
`Date Added to Library` : `After` : **01/02/2016**

This will give users 2 time format options: 
 - intelligent parsing you already implemented like `30 days ago` , `yesterday` or 
 - absolute date using ` `date_picker`.

The form field UI will still be the same with maybe a visual cue in the form of a calendar icon like below:

![image](https://cloud.githubusercontent.com/assets/87303/14399017/ecee5cfc-fde0-11e5-82e9-2e178eb3c9fd.png)

Thanks and well done.

**Comment by simon-weber** [comment]
> a date picker to differentiate relative and absolute date...

It's not clear since there's no example, but absolute datetimes will be parsed currently. I'd like to avoid changing the interface much since it's generated by third party code that's a pain to work with :grin: 

I think phrasing this more like a time range might be the way to go. What about rewording to "between now and" and "earlier than"?

This reads pretty well to me for all the cases:
* recently added:
  * date added to library between now and 30 days ago
  * date added to library between now and april 1 2016
* not heard recently:
  * last played earlier than april 1 2016
  * last played earlier than 30 days ago

We'd also want to add an absolute datetime example to the page.

**Comment by Yinka** [comment]
That should make it clearer, thanks

**Comment by simon-weber** [comment]
Thanks for the feedback!
