### ISSUE TITLE
Add conditions for date you selected "thumb up"

### ISSUE THREAD

**Issue by rcmpayne** [simon-weber/Autoplaylists-for-Google-Music#81]
If we can add a conditions that would create an autoplaylist when I liked a song. This will allow me to take my "2000 thumbs up" songs and split them in playlist of 1k items each.  

Thumbs up - 2016
Thumbs up - 2015
Thumbs up - 2014

or
Thumbs up - May 2016
Thumbs up - June 2016

**Comment by simon-weber** [comment]
Hm, that would be nice: thumbing from a date would give a nice way of looking into the past. Unfortunately, I don't think Google records this data, but I can check to see if they've added it since last I looked.

This also sounds like a vote for https://github.com/simon-weber/Autoplaylists-for-Google-Music/issues/39.

**Comment by rcmpayne** [comment]
Agreed on #39 vote as well

**Comment by simon-weber** [comment]
I haven't seen Google add any new fields recently, unfortunately. I'll reopen this if I notice something that could be used for it.
