### ISSUE TITLE
Suggestion: Make "Downloaded: a selection criteria 

### ISSUE THREAD

**Issue by feltroncq** [simon-weber/Autoplaylists-for-Google-Music#95]
I have a playlist which I listen to in the car and I do not want to use any cellular data to play the music. It would be a great help to have "Downloaded = TRUE" as a selection criteria in your tool, so I don't have to continually select "Downloaded only" in settings and then unselect it when Wifi is available. 

Thanks for a useful tool. Hopefully Google Play will introduce your functionality natively soon!

**Comment by simon-weber** [comment]
I don't think Google makes that information available to the extension, unfortunately -- download status is managed locally per device.

As a workaround, pinning a playlist on your device and [autoplaylist linking](https://groups.google.com/forum/#!topic/autoplaylists-for-google-music-announcements/Z5h9-ANfb1E) could approximate this. For example, you could manage a playlist with all your music to keep offline and pin that (rather than pinning individual songs), and then use a condition like "playlist equal to <songs to keep offline>" in your autoplaylists.

To be honest, though, it's probably more trouble than checking and unchecking "downloaded only", haha. Let me know how it goes for you.

**Comment by feltroncq** [comment]
Thanks for the response. No problem and I will continue to use the settings if that functionality is not available to us!
